blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/MuhammadAli511/usagedeck-app/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
